spring:
  application:
    name: aimking-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/aimking} # Default to local database if DB_URL is not set
    username: ${DB_USERNAME:root}                       # Default username is 'root' if DB_USERNAME is not set
    password: ${DB_PASSWORD:root}                   # Default password is 'password' if DB_PASSWORD is not set
    driver-class-name: com.mysql.cj.jdbc.Driver         # MySQL JDBC driver

  jpa:
    hibernate:
    show-sql: false                                      # Shows SQL statements in the console, for debugging purposes
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect    # Set to MySQL dialect based on version

server:
  servlet:
    context-path: /


